create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role text not null check (role in ('client', 'community')),
  email text not null,
  first_name text,
  last_name text,
  phone_number text,
  appearance text not null default 'light' check (appearance in ('light', 'dark')),
  two_factor_enabled boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.client_profiles (
  id uuid primary key references public.profiles (id) on delete cascade,
  country text,
  educational_institution text,
  position text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.community_profiles (
  id uuid primary key references public.profiles (id) on delete cascade,
  country text,
  age_span text,
  gender text,
  salary_range text,
  educational_level text,
  place_of_residence text,
  family_status text,
  interests text[] not null default '{}',
  car_count text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.surveys (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  name text not null,
  status text not null default 'published' check (status in ('draft', 'published', 'archived')),
  target_responses integer not null check (target_responses > 0),
  days_remaining integer not null default 14 check (days_remaining >= 0),
  description text not null default '',
  question_count integer,
  audience jsonb,
  questions jsonb not null default '[]'::jsonb,
  research_description text,
  research_scope text,
  hypothesis text,
  include_detailed_ai boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.survey_responses (
  id uuid primary key default gen_random_uuid(),
  survey_id bigint not null references public.surveys (id) on delete cascade,
  respondent_id uuid not null references public.profiles (id) on delete cascade,
  submitted_at timestamptz not null default timezone('utc', now()),
  completion_time_seconds integer not null check (completion_time_seconds > 0),
  trust_score integer not null check (trust_score between 0 and 100),
  earned_credits integer not null check (earned_credits >= 0),
  summary text not null default '',
  answers jsonb not null default '[]'::jsonb,
  unique (survey_id, respondent_id)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists set_client_profiles_updated_at on public.client_profiles;
create trigger set_client_profiles_updated_at
before update on public.client_profiles
for each row
execute function public.set_updated_at();

drop trigger if exists set_community_profiles_updated_at on public.community_profiles;
create trigger set_community_profiles_updated_at
before update on public.community_profiles
for each row
execute function public.set_updated_at();

drop trigger if exists set_surveys_updated_at on public.surveys;
create trigger set_surveys_updated_at
before update on public.surveys
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  user_role text;
  user_interests text[];
begin
  user_role := coalesce(new.raw_user_meta_data ->> 'role', 'community');
  user_interests :=
    case
      when jsonb_typeof(new.raw_user_meta_data -> 'interests') = 'array' then
        array(select jsonb_array_elements_text(new.raw_user_meta_data -> 'interests'))
      else
        '{}'::text[]
    end;

  insert into public.profiles (
    id,
    role,
    email,
    first_name,
    last_name,
    phone_number,
    appearance,
    two_factor_enabled
  )
  values (
    new.id,
    user_role,
    coalesce(new.email, ''),
    new.raw_user_meta_data ->> 'first_name',
    new.raw_user_meta_data ->> 'last_name',
    new.raw_user_meta_data ->> 'phone_number',
    coalesce(new.raw_user_meta_data ->> 'appearance', 'light'),
    coalesce((new.raw_user_meta_data ->> 'two_factor_enabled')::boolean, false)
  )
  on conflict (id) do update set
    role = excluded.role,
    email = excluded.email,
    first_name = excluded.first_name,
    last_name = excluded.last_name,
    phone_number = excluded.phone_number,
    appearance = excluded.appearance,
    two_factor_enabled = excluded.two_factor_enabled;

  if user_role = 'client' then
    insert into public.client_profiles (
      id,
      country,
      educational_institution,
      position
    )
    values (
      new.id,
      new.raw_user_meta_data ->> 'country',
      new.raw_user_meta_data ->> 'educational_institution',
      new.raw_user_meta_data ->> 'position'
    )
    on conflict (id) do update set
      country = excluded.country,
      educational_institution = excluded.educational_institution,
      position = excluded.position;

  else
    insert into public.community_profiles (
      id,
      country,
      age_span,
      gender,
      salary_range,
      educational_level,
      place_of_residence,
      family_status,
      interests,
      car_count
    )
    values (
      new.id,
      new.raw_user_meta_data ->> 'country',
      new.raw_user_meta_data ->> 'age_span',
      new.raw_user_meta_data ->> 'gender',
      new.raw_user_meta_data ->> 'salary_range',
      new.raw_user_meta_data ->> 'educational_level',
      new.raw_user_meta_data ->> 'place_of_residence',
      new.raw_user_meta_data ->> 'family_status',
      user_interests,
      new.raw_user_meta_data ->> 'car_count'
    )
    on conflict (id) do update set
      country = excluded.country,
      age_span = excluded.age_span,
      gender = excluded.gender,
      salary_range = excluded.salary_range,
      educational_level = excluded.educational_level,
      place_of_residence = excluded.place_of_residence,
      family_status = excluded.family_status,
      interests = excluded.interests,
      car_count = excluded.car_count;
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.client_profiles enable row level security;
alter table public.community_profiles enable row level security;
alter table public.surveys enable row level security;
alter table public.survey_responses enable row level security;

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile"
on public.profiles
for select
using (auth.uid() = id);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can view their own client profile" on public.client_profiles;
create policy "Users can view their own client profile"
on public.client_profiles
for select
using (auth.uid() = id);

drop policy if exists "Users can insert their own client profile" on public.client_profiles;
create policy "Users can insert their own client profile"
on public.client_profiles
for insert
with check (auth.uid() = id);

drop policy if exists "Users can update their own client profile" on public.client_profiles;
create policy "Users can update their own client profile"
on public.client_profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can view their own community profile" on public.community_profiles;
create policy "Users can view their own community profile"
on public.community_profiles
for select
using (auth.uid() = id);

drop policy if exists "Users can insert their own community profile" on public.community_profiles;
create policy "Users can insert their own community profile"
on public.community_profiles
for insert
with check (auth.uid() = id);

drop policy if exists "Users can update their own community profile" on public.community_profiles;
create policy "Users can update their own community profile"
on public.community_profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Clients can view their own surveys" on public.surveys;
create policy "Clients can view their own surveys"
on public.surveys
for select
using (
  user_id = auth.uid()
  and exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'client'
  )
);

drop policy if exists "Clients can create their own surveys" on public.surveys;
create policy "Clients can create their own surveys"
on public.surveys
for insert
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'client'
  )
);

drop policy if exists "Clients can update their own surveys" on public.surveys;
create policy "Clients can update their own surveys"
on public.surveys
for update
using (
  user_id = auth.uid()
  and exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'client'
  )
)
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'client'
  )
);

drop policy if exists "Clients can delete their own surveys" on public.surveys;
create policy "Clients can delete their own surveys"
on public.surveys
for delete
using (
  user_id = auth.uid()
  and exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'client'
  )
);

drop policy if exists "Community members can view published surveys" on public.surveys;
create policy "Community members can view published surveys"
on public.surveys
for select
using (
  status = 'published'
  and exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'community'
  )
);

drop policy if exists "Survey owners can view survey responses" on public.survey_responses;
create policy "Survey owners can view survey responses"
on public.survey_responses
for select
using (
  respondent_id = auth.uid()
  or exists (
    select 1
    from public.surveys
    where id = survey_id and user_id = auth.uid()
  )
);

drop policy if exists "Community members can submit survey responses" on public.survey_responses;
create policy "Community members can submit survey responses"
on public.survey_responses
for insert
with check (
  respondent_id = auth.uid()
  and exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'community'
  )
  and exists (
    select 1
    from public.surveys
    where id = survey_id and status = 'published'
  )
);
