const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {PGlite}=require('@electric-sql/pglite');
for (const missingRewards of [false, true]) test(`security migration (reward table ${missingRewards ? 'missing' : 'existing'}): privilege boundaries, capacity/debits, replay, consent and budgets`,async()=>{
 const db=new PGlite();const client='11111111-1111-4111-8111-111111111111',a='22222222-2222-4222-8222-222222222222',b='33333333-3333-4333-8333-333333333333';
 const questions=Array.from({length:5},(_,i)=>({id:'q'+i,text:'Question?',type:'Yes / No',options:['Yes','No']}));const answers=questions.map(q=>({questionId:q.id,questionText:q.text,questionType:q.type,answer:'Yes'}));
 const sql=f=>fs.readFileSync(path.join(__dirname,'../supabase',f),'utf8').replace('create extension if not exists pgcrypto;','');
 try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;`);
 await db.exec(sql('schema.sql'));
 if(missingRewards) await db.exec('drop table public.reward_activations');
 for(const [id,role]of[[client,'client'],[a,'community'],[b,'community']])await db.query('insert into auth.users values($1,$2,$3)',[id,id+'@example.invalid',{role,country:'Azerbaijan',age_span:'25-34'}]);
 for(let i=1;i<=9;i++)await db.query("insert into surveys(id,user_id,name,target_responses,question_count,questions) values($1,$2,'Synthetic',1,5,$3)",[i,client,questions]);
 for(let i=2;i<=9;i++)await db.query('insert into survey_responses(survey_id,respondent_id,completion_time_seconds,trust_score,earned_credits,answers) values($1,$2,60,100,70,$3)',[i,a,answers]);
 await db.exec("update surveys set distribution_expires_at=now()-interval '1 day' where id=9");
 await db.exec('grant usage on schema public,auth to authenticated;grant select,insert,update,delete on all tables in schema public to authenticated;grant usage,select on all sequences in schema public to authenticated;');
 await db.exec(sql('migrate-survey-pricing-orders.sql'));await db.exec(sql('migrate-prelaunch-security.sql'));await db.exec(sql('migrate-prelaunch-security.sql'));
 await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[a]);
 await assert.rejects(db.query("update profiles set email='admin@example.invalid' where id=$1",[a]),/permission denied/);
 await assert.rejects(db.query("update profiles set role='client' where id=$1",[a]),/permission denied/);
 await db.query("update profiles set first_name='Allowed' where id=$1",[a]);
 await assert.rejects(db.query('insert into survey_responses(survey_id,respondent_id,completion_time_seconds,trust_score,earned_credits) values(1,$1,1,100,1000000)',[a]),/permission denied/);
 await assert.rejects(db.query("insert into reward_activations(member_id,reward_id,reward_company,reward_subtitle,activation_email,credits,status) values($1,'notion','Notion','test','test@example.invalid',1,'fulfilled')",[a]),/permission denied/);
 await assert.rejects(db.query('select redeem_reward($1,$2,$3)',[a,'notion','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa']),/permission denied/);
 await assert.rejects(db.query("update community_profiles set age_span='13-17' where id=$1",[a]),/adults/);
 await db.exec('reset role');
 const versions=async member=>{const s=(await db.query('select updated_at from surveys where id=1')).rows[0];const m=(await db.query('select updated_at from community_profiles where id=$1',[member])).rows[0];return[s.updated_at,m.updated_at]};
 const submit=async(member,credits=70,sv)=>db.query('select submit_verified_response($1,1,$2,$3,60,100,$4,$5,$6,$7) as response',[member,...(sv??await versions(member)),credits,'Synthetic verified answer',answers,'fallback']);
 await assert.rejects(submit(a,1000000),/Invalid verified response/);
 const expired=(await db.query('select updated_at from surveys where id=9')).rows[0].updated_at;
 const bVersion=(await versions(b))[1];
 await assert.rejects(db.query('select submit_verified_response($1,9,$2,$3,60,100,70,$4,$5,$6)',[b,expired,bVersion,'Synthetic',answers,'fallback']),/closed/);
 const av=await versions(a),bv=await versions(b);
 const results=await Promise.allSettled([submit(a,70,av),submit(b,70,bv)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);
 assert.equal((await db.query('select count(*)::int as n from survey_responses where survey_id=1')).rows[0].n,1);
 assert.equal((await db.query('select status from surveys where id=1')).rows[0].status,'archived');
 const again=await submit(a,70,av);assert.equal(again.rows[0].response.earned_credits,70);
 const r1='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',r2='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
 const redeem=id=>db.query("select redeem_reward($1,'notion',$2) as result",[a,id]);
 const spends=await Promise.allSettled([redeem(r1),redeem(r2)]);assert.equal(spends.filter(x=>x.status==='fulfilled').length,1);
 assert.equal((await db.query('select sum(credits)::int as spent from reward_activations')).rows[0].spent,560);
 await db.exec('set role authenticated');
 assert.equal((await db.query('select count(*)::int as n from reward_activations')).rows[0].n,1);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[b]);
 assert.equal((await db.query('select count(*)::int as n from reward_activations')).rows[0].n,0);
 await db.exec('reset role');
 const repeated=await redeem(r1);assert.equal(repeated.rows[0].result.activation.credits,560);assert.equal((await db.query('select count(*)::int as n from reward_activations')).rows[0].n,1);
 await assert.rejects(db.query("select redeem_reward($1,'withdraw-cash',$2)",[a,r1]),/Idempotency/);
 await assert.rejects(db.query('update surveys set target_responses=1000 where id=2'),/Historical/);
 await assert.rejects(db.query('update surveys set include_detailed_ai=true where id=2'),/Historical/);
 await assert.rejects(db.query("update surveys set status='published' where id=1"),/Historical/);
 await assert.rejects(db.query("insert into auth.users values('44444444-4444-4444-8444-444444444444','young@example.invalid',$1)",[{role:'community',country:'Azerbaijan',age_span:'13-17',adult_confirmed:true,terms_version:'2026-03-27',privacy_policy_version:'2026-03-27'}]),/adults/);
 await assert.rejects(db.query("insert into auth.users values('44444444-4444-4444-8444-444444444444','adult@example.invalid',$1)",[{role:'client'}]),/consent/);
 await db.query("insert into auth.users values('44444444-4444-4444-8444-444444444444','adult@example.invalid',$1)",[{role:'community',country:'Azerbaijan',age_span:'18-24',adult_confirmed:true,terms_version:'2026-03-27',privacy_policy_version:'2026-03-27'}]);
 assert((await db.query("select adult_confirmed_at from profiles where id='44444444-4444-4444-8444-444444444444'")).rows[0].adult_confirmed_at);
 const orderId='55555555-5555-4555-8555-555555555555';
 await db.query("insert into survey_orders(id,user_id,checkout_id,currency,total_cents,question_count,response_count,include_detailed_report,pricing_version,pricing,status) values($1,$2,'synthetic-checkout','USD',10000,5,50,false,'survey-formula-v1','{}','paid')",[orderId,client]);
 await db.query("insert into surveys(id,user_id,name,target_responses,question_count,questions,pricing_order_id) values(10,$1,'Refund fixture',50,5,$2,$3)",[client,questions,orderId]);
 await db.query("select record_survey_refund('synthetic-checkout')");
 await db.query("select record_survey_refund('synthetic-checkout')");
 assert.equal((await db.query('select status from surveys where id=10')).rows[0].status,'archived');
 await assert.rejects(db.query("update surveys set status='published' where id=10"),/Refunded/);
 assert.equal((await db.query('select refund_status from survey_orders where id=$1',[orderId])).rows[0].refund_status,'refunded');
 await db.query("select acquire_ai_request($1,'questions')",[client]);await db.query("select acquire_ai_request($1,'questions')",[client]);await assert.rejects(db.query("select acquire_ai_request($1,'questions')",[client]),/concurrency/);
 await db.exec('delete from ai_request_leases');
 for(let i=2;i<30;i++){await db.query("select acquire_ai_request($1,'questions')",[client]);await db.exec('delete from ai_request_leases')}
 await assert.rejects(db.query("select acquire_ai_request($1,'questions')",[client]),/limit reached/);
 }finally{await db.close()}
});
