const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const Module=require('node:module');const ts=require('typescript');
const root=path.resolve(__dirname,'..'),mocks=new Map(),original=Module._load;
Module._load=function(id,parent,main){if(mocks.has(id))return mocks.get(id);if(id==='server-only')return {};return original.call(this,id.startsWith('@/')?path.join(root,id.slice(2)):id,parent,main)};
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,f);
const load=f=>{const full=path.join(root,f);delete require.cache[require.resolve(full)];return require(full)};
const request=body=>new Request('https://mergen.example/api/test',{method:'POST',body:JSON.stringify(body)});
const q=[{id:'q1',text:'Why?',type:'Open question',options:['Free-text response']}],answers=[{questionId:'q1',questionText:'Forged prompt',questionType:'Ranking',answer:'A thoughtful synthetic answer.'}];
test('F03 admin authorization ignores mutable profile email; confirmed auth identity and configured IDs govern access',async()=>{
 const before=process.env.ADMIN_EMAIL,ids=process.env.ADMIN_USER_IDS;process.env.ADMIN_EMAIL='admin@example.invalid';delete process.env.ADMIN_USER_IDS;
 let auth={user:{id:'member',email:'member@example.invalid',email_confirmed_at:'yes'},profile:{id:'member',role:'community',email:'admin@example.invalid'}};
 mocks.set('@/lib/supabase/profile-server',{getCurrentUserProfile:async()=>auth,getDashboardPathForRole:()=>'/community'});mocks.set('next/navigation',{redirect:()=>{throw new Error('DENIED')}});
 try{const {requireAdminProfile}=load('lib/admin-access.ts');await assert.rejects(requireAdminProfile(),/DENIED/);auth.user.email='admin@example.invalid';assert(await requireAdminProfile());auth.user.email_confirmed_at=null;await assert.rejects(requireAdminProfile(),/DENIED/);process.env.ADMIN_USER_IDS='member';assert(await requireAdminProfile());process.env.ADMIN_USER_IDS='other';await assert.rejects(requireAdminProfile(),/DENIED/);}finally{if(before===undefined)delete process.env.ADMIN_EMAIL;else process.env.ADMIN_EMAIL=before;if(ids===undefined)delete process.env.ADMIN_USER_IDS;else process.env.ADMIN_USER_IDS=ids;mocks.clear()}
});
test('F06 verification paths reject external, protocol-relative, control-character and backslash destinations',()=>{
 const {safeVerificationPath}=load('lib/security/redirect.ts');for(const bad of [null,'https://external.invalid','//external.invalid','/\\external.invalid','\n//external.invalid','javascript:alert(1)','/\texternal'])assert.equal(safeVerificationPath(bad),'/auth');assert.equal(safeVerificationPath('/dashboard/client?payment=success'),'/dashboard/client?payment=success');
});
test('F20 local preview fails closed in production and requires admin in opted-in development',async()=>{
 const old=process.env.NODE_ENV,flag=process.env.ENABLE_LOCAL_ADMIN_PREVIEW;let checks=0;mocks.set('next/navigation',{notFound:()=>{throw new Error('NOT_FOUND')}});mocks.set('@/lib/admin-access',{requireAdminProfile:async()=>{checks++;throw new Error('ADMIN_REQUIRED')}});
 try{const {requireLocalPreviewAccess}=load('lib/local-preview-access.ts');process.env.NODE_ENV='production';process.env.ENABLE_LOCAL_ADMIN_PREVIEW='true';await assert.rejects(requireLocalPreviewAccess(),/NOT_FOUND/);assert.equal(checks,0);process.env.NODE_ENV='development';await assert.rejects(requireLocalPreviewAccess(),/ADMIN_REQUIRED/);assert.equal(checks,1)}finally{process.env.NODE_ENV=old;if(flag===undefined)delete process.env.ENABLE_LOCAL_ADMIN_PREVIEW;else process.env.ENABLE_LOCAL_ADMIN_PREVIEW=flag;mocks.clear()}
});
test('F01/F08 answer validator uses stored question text and rejects missing, duplicate, foreign and invalid answers',()=>{
 const {validateAnswers,validateDuration}=load('lib/security/answers.ts');assert.equal(validateAnswers(q,answers)[0].questionText,'Why?');for(const input of [[],[...answers,...answers],[{questionId:'foreign',answer:'x'}],[{questionId:'q1',answer:{}}]])assert.throws(()=>validateAnswers(q,input));for(const v of [NaN,Infinity,0,-1,1.5,'2',86401])assert.throws(()=>validateDuration(v));assert.throws(()=>validateAnswers([{id:'q1',text:'?',type:'Yes / No',options:['Yes','No']}],[{questionId:'q1',answer:'Maybe'}]));
});
test('F01 actual submission ignores browser award fields and returns authoritative stored award',async()=>{
 let written,evaluated;const admin={from:table=>({select:()=>({eq(){return this},maybeSingle:async()=>({data:table==='survey_attempts'?{started_at:new Date(Date.now()-60000).toISOString()}:null,error:null})})}),rpc:async(name,args)=>{written=args;return{data:{id:'r1',earned_credits:45,trust_score:50,summary:'Verified',evaluation_source:'fallback',completion_time_seconds:60},error:null}}};
 mocks.set('@/lib/survey-authorization',{requireAuthorizedProfile:async()=>({profile:{id:'member'},response:null})});mocks.set('@/lib/supabase/admin',{createAdminClient:()=>admin});mocks.set('@/lib/server-survey-submission',{loadEligibleSurvey:async()=>({survey:{name:'Stored survey',description:'Stored description',questions:q,updated_at:'now'},member:{updated_at:'now'}})});mocks.set('@/lib/security/ai-budget',{withAiBudget:async(_u,_s,fn)=>fn()});mocks.set('@/lib/server-trust-evaluation',{evaluateSurveyResponse:async input=>{evaluated=input;return{trustScore:50,credits:45,summary:'Verified',source:'fallback'}}});
 try{const {POST}=load('app/api/surveys/[surveyId]/responses/route.ts');const r=await POST(request({answers,earnedCredits:1000000,trustScore:100,completionTimeSeconds:99999}),{params:Promise.resolve({surveyId:'1'})});assert.equal(r.status,200);assert.equal((await r.json()).earnedCredits,45);assert.equal(written.p_credits,45);assert.equal(written.p_score,50);assert.equal(evaluated.answers[0].questionText,'Why?');assert(evaluated.completionTimeSeconds<65);const bad=await POST(request({answers:[]}),{params:Promise.resolve({surveyId:'1'})});assert.equal(bad.status,400);}finally{mocks.clear()}
});
test('F07 anonymous AI requests never reach provider',async()=>{
 let calls=0;const prev=global.fetch;global.fetch=async()=>{calls++;throw new Error('unexpected provider')};mocks.set('@/lib/survey-authorization',{requireAuthorizedProfile:async()=>({profile:null,response:Response.json({error:'Unauthorized'},{status:401})})});try{for(const f of ['app/api/survey-assistant/route.ts','app/api/survey-trust-score/route.ts'])assert.equal((await load(f).POST(request({surveyTitle:123}))).status,401);assert.equal(calls,0)}finally{global.fetch=prev;mocks.clear()}
});
test('F08 malformed model scores and provider failures produce finite bounded server fallback',async()=>{
 const key=process.env.GEMINI_API_KEY,prev=global.fetch;process.env.GEMINI_API_KEY='synthetic';try{const {evaluateSurveyResponse}=load('lib/server-trust-evaluation.ts');for(const value of [NaN,'100',101,-1,null]){global.fetch=async()=>Response.json({candidates:[{content:{parts:[{text:JSON.stringify({trustScore:value,summary:'test',strengths:[{}],risks:[]})}]}}]});const r=await evaluateSurveyResponse({surveyTitle:'Test',questions:q,answers:load('lib/security/answers.ts').validateAnswers(q,answers),completionTimeSeconds:60});assert.equal(r.source,'fallback');assert(Number.isFinite(r.credits));assert(r.credits>=20&&r.credits<=70)}global.fetch=async()=>{throw new DOMException('timeout','TimeoutError')};assert.equal((await evaluateSurveyResponse({surveyTitle:'Test',questions:q,answers,completionTimeSeconds:60})).source,'fallback')}finally{global.fetch=prev;if(key===undefined)delete process.env.GEMINI_API_KEY;else process.env.GEMINI_API_KEY=key}
});
test('F13 webhook signatures, timestamp replay rejection, idempotent processing and refund dispatch',async()=>{
 const {Webhook}=require('standardwebhooks');const secret='synthetic-polar-webhook-secret',old=process.env.POLAR_WEBHOOK_SECRET;process.env.POLAR_WEBHOOK_SECRET=secret;const saved=new Set();let fulfills=0,refunds=0;const admin={from:table=>({select:()=>({eq(_k,id){this.id=id;return this},maybeSingle:async function(){return{data:table==='payment_webhook_events'?(saved.has(this.id)?{id:this.id}:null):{user_id:'client',refund_status:null},error:null}}}),upsert:async value=>{saved.add(value.id);return{error:null}}}),rpc:async()=>{refunds++;return{error:null}}};mocks.set('@/lib/supabase/admin',{createAdminClient:()=>admin});mocks.set('@/lib/survey-fulfillment',{fulfillSurveyOrder:async()=>{fulfills++;return{}}});
 const make=(type,id='evt1',valid=true,date=new Date())=>{const body=JSON.stringify({type,data:{id:'checkout',checkout_id:'checkout',status:'succeeded'}});return new Request('https://mergen.example/api/polar/webhook',{method:'POST',body,headers:{'webhook-id':id,'webhook-timestamp':String(Math.floor(date.getTime()/1000)),'webhook-signature':valid?new Webhook(Buffer.from(secret).toString('base64')).sign(id,date,body):'bad'}})};
 try{const {POST}=load('app/api/polar/webhook/route.ts');assert.equal((await POST(make('checkout.updated','bad',false))).status,401);assert.equal((await POST(make('checkout.updated','old',true,new Date(0)))).status,401);assert.equal((await POST(make('checkout.updated'))).status,200);assert.equal((await POST(make('checkout.updated'))).status,200);assert.equal(fulfills,1);assert.equal((await POST(make('order.refunded','refund'))).status,200);assert.equal(refunds,1)}finally{if(old===undefined)delete process.env.POLAR_WEBHOOK_SECRET;else process.env.POLAR_WEBHOOK_SECRET=old;mocks.clear()}
});
test('oversized and non-object JSON are rejected before business logic',async()=>{const {readJsonObject}=load('lib/security/request.ts');await assert.rejects(readJsonObject(request({text:'x'.repeat(100)}),20),e=>e.status===413);for(const v of [null,[],123])await assert.rejects(readJsonObject(request(v)));});
test('F13 fulfillment uses durable draft and returns the same survey on retry',async()=>{
 let inserted=null,inserts=0;
 const draft={title:'Original stored title',description:'Synthetic',researchDescription:'Synthetic',researchScope:'Scope',hypothesis:'Hypothesis',questionCount:5,targetResponses:50,includeDetailedAI:false,audience:{countries:['Azerbaijan'],ageMin:18,ageMax:80,gender:'All genders',education:'Any education level',interests:[],researchArea:'Education'},questions:Array.from({length:5},(_,i)=>({id:'q'+i,text:'Synthetic?',type:'Yes / No',options:['Yes','No']}))};
 const order={id:'order',user_id:'client',question_count:5,response_count:50,include_detailed_report:false,draft_payload:draft};
 const db={from:()=>({select:()=>({eq(){return this},maybeSingle:async()=>({data:inserted,error:null}),single:async()=>({data:inserted,error:null})}),insert:data=>{inserts++;inserted={id:1,...data};return{select:()=>({single:async()=>({data:inserted,error:null})})}}})};
 mocks.set('@/lib/survey-orders',{verifySurveyOrder:async(_id,owner)=>{assert.equal(owner,'client');return{order,isPaid:true}}});mocks.set('@/lib/supabase/admin',{createAdminClient:()=>db});mocks.set('@/lib/survey-db',{buildSurveyInsertPayload:(payload,userId)=>({name:payload.title,user_id:userId}),mapSurveyRowToClientSurvey:row=>row});
 try{const {fulfillSurveyOrder}=load('lib/survey-fulfillment.ts');const one=await fulfillSurveyOrder('checkout','client');const two=await fulfillSurveyOrder('checkout','client');assert.equal(one.name,'Original stored title');assert.equal(two.id,one.id);assert.equal(inserts,1);}finally{mocks.clear()}
});
test('F04 server rejects ineligible audiences before scoring or writing a response',async()=>{
 const survey={id:1,status:'published',days_remaining:3,distribution_expires_at:new Date(Date.now()+86400000).toISOString(),distribution_stage:1,audience:{countries:['Turkey'],ageMin:60,ageMax:80,gender:'Female',education:'Doctorate',interests:['Finance'],generalAudience:false}};
 const member={age_span:'18-24',country:'Azerbaijan',gender:'Male',educational_level:'High school',interests:[]};
 mocks.set('@/lib/supabase/admin',{createAdminClient:()=>({from:table=>({select:()=>({eq(){return this},maybeSingle:async()=>({data:table==='surveys'?survey:member,error:null})})})})});
 try{await assert.rejects(load('lib/server-survey-submission.ts').loadEligibleSurvey('member',1),e=>e.status===403)}finally{mocks.clear()}
});
