export const countryOptions = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

export const clientPositionOptions = [
  "Student",
  "Graduate Student",
  "PhD Candidate",
  "Research Assistant",
  "Researcher",
  "Academician",
  "Lecturer",
  "Professor",
  "Administrator",
  "Policy Analyst",
  "Other"
];

export const ageSpanOptions = ["18-24", "25-34", "35-44", "45-54", "55-64", "65+"];

export const genderOptions = ["Female", "Male", "Non-binary", "Prefer not to say"];

export const salaryRangeOptions = [
  "Up to $500",
  "Up to $1,000",
  "Up to $2,500",
  "Up to $5,000",
  "Up to $10,000",
  "$10,000+"
];

export const employmentStatusOptions = [
  "Student",
  "Employed full-time",
  "Employed part-time",
  "Self-employed",
  "Freelance / Contract",
  "Unemployed",
  "Homemaker / Caregiver",
  "Retired",
  "Prefer not to say"
];

export const industryOptions = [
  "Technology",
  "Healthcare",
  "Education",
  "Finance",
  "Government",
  "Retail and E-commerce",
  "Manufacturing",
  "Media and Entertainment",
  "Hospitality and Tourism",
  "Transportation and Logistics",
  "Energy and Utilities",
  "Construction and Real Estate",
  "Legal Services",
  "Nonprofit / NGO",
  "Agriculture",
  "Not currently working / Not applicable",
  "Other"
];

export const educationLevelOptions = [
  "Uneducated",
  "High School",
  "Undergraduate",
  "Bachelor's Degree",
  "Master's Degree",
  "Doctorate",
];

export const fieldOfStudyOptions = [
  "Computer Science",
  "Engineering",
  "Business and Management",
  "Economics",
  "Finance and Accounting",
  "Education",
  "Psychology",
  "Sociology",
  "Political Science",
  "Law",
  "Medicine and Health Sciences",
  "Biology and Life Sciences",
  "Physical Sciences",
  "Mathematics and Statistics",
  "Environmental Studies",
  "Arts and Humanities",
  "Communications and Media",
  "Architecture and Design",
  "Agriculture and Food Sciences",
  "Not currently studying / Not applicable",
  "Other"
];

export const residenceOptions = [
  "City (Urban area)",
  "Suburban area (City outskirts)",
  "Town",
  "Village (Rural area)"
];

export const familyStatusOptions = [
  "Single",
  "Married",
  "In a relationship",
  "Divorced",
  "Widowed",
  "Prefer not to say"
];

export const householdSizeOptions = ["1", "2", "3", "4", "5", "6", "7+"];

export const childrenCountOptions = ["0", "1", "2", "3", "4+"];

export const englishLevelOptions = [
  "Basic",
  "Intermediate",
  "Upper-intermediate",
  "Advanced",
  "Fluent",
  "Native / Bilingual",
  "Prefer not to say"
];

export const languageSkillOptions = [
  "English",
  "Spanish",
  "French",
  "German",
  "Turkish",
  "Azerbaijani",
  "Arabic",
  "Persian",
  "Russian",
  "Hindi",
  "Urdu",
  "Bengali",
  "Portuguese",
  "Italian",
  "Chinese (Mandarin)",
  "Japanese",
  "Korean",
  "Indonesian",
  "Malay",
  "Vietnamese"
];

export const interestOptions = [
  "Technology",
  "Education",
  "Health",
  "Business",
  "Finance",
  "Science",
  "Travel",
  "Food",
  "Gaming",
  "Sports",
  "Environment",
  "Fashion",
  "Art and Design",
  "Media and Entertainment",
  "Politics and Society"
];

export const carCountOptions = ["0", "1", "2+"];

export const popularUniversities = [
  "Harvard University",
  "Stanford University",
  "Massachusetts Institute of Technology",
  "University of Oxford",
  "University of Cambridge",
  "University of Toronto",
  "National University of Singapore",
  "Tsinghua University",
  "University of Melbourne",
  "ETH Zurich",
  "University of Tokyo",
  "Seoul National University",
  "Peking University",
  "Middle East Technical University",
  "University of Bologna",
  "Sorbonne University",
  "Technical University of Munich",
  "Azerbaijan State Oil and Industry University",
  "Baku State University",
  "Other"
];
